services:
  postgres:
    image: postgres:16
    container_name: rag_summarizer_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_tca
      POSTGRES_DB: tca_chatbot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
